<?php
/**
 * Fix historial v2:
 * 1. Delete March 2026 estandares snapshots (were calculated with wrong year filter)
 * 2. Set Feb 2026 plan trabajo to 100% abiertas for all clients (baseline = all open)
 *
 * Usage: DB_PROD_PASS=xxx php fix_historial_2026_v2.php production
 */

$env = $argv[1] ?? 'local';

if ($env === 'production') {
    $host = 'db-mysql-cycloid-do-user-18794030-0.h.db.ondigitalocean.com';
    $port = 25060;
    $user = 'cycloid_userdb';
    $pass = getenv('DB_PROD_PASS');
    $db   = 'propiedad_horizontal';
    if (!$pass) die("ERROR: DB_PROD_PASS env var not set\n");
} else {
    $host = 'localhost';
    $port = 3306;
    $user = 'root';
    $pass = '';
    $db   = 'propiedad_horizontal';
}

echo "Connecting to {$env} ({$host}:{$port})...\n";
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$conn = new mysqli($host, $user, $pass, $db, $port);

// 1. Delete March 2026 estandares (bad data from year-filtered snapshot)
echo "\n=== Deleting March 2026 ESTANDARES snapshots ===\n";
$conn->query("DELETE FROM historial_resumen_estandares WHERE YEAR(fecha_extraccion) = 2026 AND MONTH(fecha_extraccion) = 3");
echo "Deleted: {$conn->affected_rows} rows\n";

// 2. Delete March 2026 plan trabajo too (will be re-generated by liquidar)
echo "\n=== Deleting March 2026 PLAN TRABAJO snapshots ===\n";
$conn->query("DELETE FROM historial_resumen_plan_trabajo WHERE YEAR(fecha_extraccion) = 2026 AND MONTH(fecha_extraccion) = 3");
echo "Deleted: {$conn->affected_rows} rows\n";

// 3. Set Feb plan trabajo to 100% abiertas (baseline: all activities open at start of cycle)
echo "\n=== Updating Feb 2026 PLAN TRABAJO → 100% abiertas ===\n";
$conn->query("UPDATE historial_resumen_plan_trabajo SET porcentaje_abiertas = 100.00 WHERE YEAR(fecha_extraccion) = 2026 AND MONTH(fecha_extraccion) IN (1, 2)");
echo "Updated: {$conn->affected_rows} rows\n";

// 4. Verify
echo "\n=== Verification: All 2026 ESTANDARES ===\n";
$res = $conn->query("SELECT id_cliente, porcentaje_cumplimiento, fecha_extraccion FROM historial_resumen_estandares WHERE YEAR(fecha_extraccion) = 2026 ORDER BY fecha_extraccion, id_cliente LIMIT 10");
while ($row = $res->fetch_assoc()) {
    echo "  Cliente {$row['id_cliente']}: {$row['porcentaje_cumplimiento']}% @ {$row['fecha_extraccion']}\n";
}
echo "  ...(showing first 10)\n";

echo "\n=== Verification: All 2026 PLAN TRABAJO ===\n";
$res2 = $conn->query("SELECT id_cliente, porcentaje_abiertas, fecha_extraccion FROM historial_resumen_plan_trabajo WHERE YEAR(fecha_extraccion) = 2026 ORDER BY fecha_extraccion, id_cliente LIMIT 10");
while ($row = $res2->fetch_assoc()) {
    echo "  Cliente {$row['id_cliente']}: {$row['porcentaje_abiertas']}% @ {$row['fecha_extraccion']}\n";
}
echo "  ...(showing first 10)\n";

echo "\nDone!\n";
$conn->close();
